/** Public RPC surface. Internal helpers and directory access mutations are never exposed. */
const rpcMethods: Record<string, ReadonlySet<string>> = {
  admin: new Set(['fetchNewsletters', 'fetchNewsletterTemplates', 'fetchNewsletter', 'fetchNewsletterByWeek', 'createNewsletter', 'updateNewsletter', 'getNewsletterPublishReadiness', 'createTemplateFromNewsletter', 'createNewsletterFromTemplate', 'previewNewsletterPublishAudience', 'fetchNewsletterDeliveryBatches', 'fetchNewsletterDeliveryRecipients', 'archiveNewsletter', 'deleteNewsletter', 'fetchArticlesByNewsletter', 'fetchArticlesByNewsletterId', 'fetchAllArticles', 'fetchDeletedArticles', 'fetchArticleVersionHistory', 'restoreArticleVersion', 'updateArticle', 'deleteArticle', 'restoreDeletedArticle', 'purgeDeletedArticle', 'addArticleToNewsletter', 'addArticleToNewsletterById', 'removeArticleFromNewsletter', 'removeArticleFromNewsletterById', 'updateArticleTargetingInNewsletterById', 'getNewslettersForArticle', 'fetchArticleNewsletterMemberships', 'fetchArticleCategories', 'createArticleCategory', 'updateArticleCategory', 'activateArticleCategory', 'deactivateArticleCategory', 'fetchArticleTags', 'createArticleTag', 'updateArticleTag', 'activateArticleTag', 'deactivateArticleTag', 'fetchArticleTaxonomyAssignments', 'updateArticleTaxonomyAssignments', 'getAvailableArticles', 'getAvailableArticlesByNewsletterId', 'reorderArticlesInNewsletter', 'reorderArticlesInNewsletterById', 'createArticleForNewsletter', 'fetchArticlesByNewsletterViaJunction', 'fetchClasses', 'createClass', 'updateClass', 'deleteClass', 'activateClass', 'deactivateClass', 'addStudentToClass', 'removeStudentFromClass', 'fetchFamilies', 'createFamily', 'updateFamily', 'deleteFamily', 'activateFamily', 'deactivateFamily', 'getFamilyMembers', 'addParentToFamily', 'removeParentFromFamily', 'updateParentRelationship', 'addStudentToFamily', 'removeStudentFromFamily', 'addStudentToClassEnrollment', 'removeStudentFromClassEnrollment', 'getAvailableParents', 'getAvailableStudents', 'fetchStudents', 'createStudent', 'updateStudent', 'activateStudent', 'deactivateStudent', 'deleteStudent', 'fetchParents', 'updateParent', 'fetchTeachers', 'fetchTeacherAssignedClasses', 'fetchUserClassRestrictions', 'fetchAccessControlLogs', 'fetchUsers', 'linkParentToStudent', 'unlinkParentFromStudent', 'getParentStudents', 'getParentStudentRelationships']),
  emailTemplate: new Set(['normalizeImportedBodyHtml', 'listTemplates', 'createTemplate', 'updateTemplateRevision', 'syncFileTemplate', 'duplicateTemplate', 'deleteTemplate', 'setActiveTemplate', 'getCurrentRevision', 'getRevisionById', 'previewRevision', 'previewBlock']),
  newsletterDelivery: new Set(['previewAudience', 'previewPersonalizationForFamily', 'listBatchesForNewsletter', 'listBatchRecipients', 'fetchBatch']),
  fileEmailTemplate: new Set(['listSources', 'previewSource']),
 }
export function isAllowedRpc(service: string, method: string): boolean {
  return Object.hasOwn(rpcMethods, service) && rpcMethods[service].has(method)
}
